site_name: CloudStack Docs
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - index.md
  - Tutoriais:
    - tutoriais/primeira-instancia.md
    - tutoriais/apl-autoscaling.md
