site_name: CloudStack Docs
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
markdown_extensions:
  - footnotes
nav:
  - index.md
  - Tutorial:
    - tutorial/primeira-instancia.md